[build]
ignore = "git diff --quiet HEAD^ HEAD .."

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"
